{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pa-webinar.fullname" . }}
  labels:
    {{- include "pa-webinar.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pa-webinar.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path | default "/api/metrics" }}
      interval: {{ .Values.metrics.serviceMonitor.interval | default "15s" }}
      {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.metrics.bearerTokenSecret }}
      bearerTokenSecret:
        name: {{ .Values.metrics.bearerTokenSecret.name }}
        key: {{ .Values.metrics.bearerTokenSecret.key }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
